### ISSUE TITLE
Remove and revoke the api key

### ISSUE THREAD

**Issue by metebilgin** [COMU/kripton-guard#3]
Need to remove and revoke the api key from the configuration file.
kripton-guard/kripton-guard.conf

**Comment by okanozdemir** [comment]
Firebase Cloud Messaging server API key has been removed from configuration file and it is invalid. Notifications are now sent with Google Cloud Functions, not with Python. 

Read and write operations in the Realtime Database require authentication, so the API keys still exist but this is not a security issue.
